
name: DEPLOY_FLEETDEV

on:
 push:
  branches: [ master ]
jobs:
 deploy_project:
    runs-on: ubuntu-latest
    steps:
      - name: copy file via ssh password
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.DEPLOY_SERVER_HOST }}
          username: ${{ secrets.DEPLOY_SERVER_USERNAME }}
          password: ${{ secrets.DEPLOY_SERVER_PASSWORD }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          source: "agroru-test"
          target: "/usr/share/nginx"

